import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Stitch Onyx Ledger V3 color tokens
        "surface-tint": "#5e5e5e",
        "secondary": "#006e2f",
        "secondary-container": "#5bf083",
        "secondary-fixed": "#4ae176",
        "secondary-fixed-dim": "#21c45d",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#002109",
        "on-secondary-fixed": "#002109",
        "on-secondary-fixed-variant": "#00461b",
        "tertiary": "#00397f",
        "tertiary-container": "#2170e4",
        "tertiary-fixed": "#005ac2",
        "tertiary-fixed-dim": "#004395",
        "on-tertiary": "#d8e2ff",
        "on-tertiary-container": "#ffffff",
        "on-tertiary-fixed": "#ffffff",
        "on-tertiary-fixed-variant": "#d8e2ff",
        "primary": "#000000",
        "primary-container": "#3b3b3b",
        "primary-fixed": "#5e5e5e",
        "primary-fixed-dim": "#474747",
        "on-primary": "#e2e2e2",
        "on-primary-container": "#ffffff",
        "on-primary-fixed": "#ffffff",
        "on-primary-fixed-variant": "#e2e2e2",
        "background": "#f9f9f9",
        "surface": "#f9f9f9",
        "surface-dim": "#dadada",
        "surface-bright": "#f9f9f9",
        "surface-variant": "#e2e2e2",
        "surface-container": "#eeeeee",
        "surface-container-low": "#f3f3f3",
        "surface-container-high": "#e8e8e8",
        "surface-container-highest": "#e2e2e2",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#1a1c1c",
        "on-surface-variant": "#474747",
        "on-background": "#1a1c1c",
        "outline": "#777777",
        "outline-variant": "#c6c6c6",
        "inverse-surface": "#2f3131",
        "inverse-on-surface": "#f1f1f1",
        "inverse-primary": "#c6c6c6",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#410002",
      },
      borderRadius: {
        DEFAULT: "0px",
        sm: "0px",
        md: "0px",
        lg: "0px",
        xl: "0px",
        "2xl": "0px",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Space Grotesk", "sans-serif"],
        mono: ["Roboto Mono", "monospace"],
      },
    },
  },
  plugins: [],
};

export default config;
