package com.pnltracker.solana.defi.service;

import java.util.List;

import org.springframework.stereotype.Component;

import com.pnltracker.solana.defi.model.SolanaTokenizedDefiAssetDefinition;

@Component
public class SolanaTokenizedDefiFallbackRegistry {

    private static final List<SolanaTokenizedDefiAssetDefinition> DEFINITIONS = List.of(
            new SolanaTokenizedDefiAssetDefinition(
                    "J1toso1uCk3RLmjorhTtrVwY9HJ7X8V9yYac6Y7kGCPn",
                    "JitoSOL",
                    "jito",
                    "Jito",
                    "LIQUID_STAKING",
                    9,
                    "official_jito_docs",
                    "VERIFIED",
                    true,
                    true),
            new SolanaTokenizedDefiAssetDefinition(
                    "mSoLzYCxHdYgdzU16g5QSh3i5K3z3KZK7ytfqcJm7So",
                    "mSOL",
                    "marinade",
                    "Marinade",
                    "LIQUID_STAKING",
                    9,
                    "official_marinade_docs",
                    "VERIFIED",
                    true,
                    true),
            new SolanaTokenizedDefiAssetDefinition(
                    "bSo13r4TkiE4KumL71LsHTPpL2euBYLFx6h9HP3piy1",
                    "bSOL",
                    "blazestake",
                    "BlazeStake",
                    "LIQUID_STAKING",
                    9,
                    "official_blazestake_docs",
                    "VERIFIED",
                    true,
                    true),
            new SolanaTokenizedDefiAssetDefinition(
                    "5oVNBeEEQvYi1cX3ir8Dx5n1P7pdxydbGF2X4TxVusJm",
                    "INF",
                    "sanctum",
                    "Sanctum",
                    "LIQUID_STAKING",
                    9,
                    "official_sanctum_docs",
                    "VERIFIED",
                    true,
                    true),
            new SolanaTokenizedDefiAssetDefinition(
                    "jupSoLaHXQiZZTSfEWMTRRgpnyFm8f6sZdosWBjx93v",
                    "JupSOL",
                    "jupiter",
                    "Jupiter",
                    "LIQUID_STAKING",
                    9,
                    "jupiter_verified_token_api",
                    "VERIFIED",
                    true,
                    true),
            new SolanaTokenizedDefiAssetDefinition(
                    "BonK1YhkXEGLZzwtcvRTip3gAL9nCeQD7ppZBLXhtTs",
                    "bonkSOL",
                    "bonk",
                    "Bonk",
                    "LIQUID_STAKING",
                    9,
                    "official_sanctum_docs",
                    "VERIFIED",
                    true,
                    true),
            new SolanaTokenizedDefiAssetDefinition(
                    "pWrSoLAhue6jUxUkbWgmEy5rD9VJzkFmvfTDV5KgNuu",
                    "pwrSOL",
                    "power",
                    "Power Staked SOL",
                    "LIQUID_STAKING",
                    9,
                    "official_sanctum_docs",
                    "VERIFIED",
                    true,
                    true),
            new SolanaTokenizedDefiAssetDefinition(
                    "LSTxxxnJzKDFSLr4dUkPcmCf5VyryEqzPLz5j4bpxFp",
                    "LST",
                    "marginfi",
                    "MarginFi",
                    "LIQUID_STAKING",
                    9,
                    "jupiter_verified_token_api",
                    "VERIFIED",
                    true,
                    true),
            new SolanaTokenizedDefiAssetDefinition(
                    "pSo1f9nQXWgXibFtKf7NWYxb5enAM4qfP6UJSiXRQfL",
                    "PSOL",
                    "phantom",
                    "Phantom SOL",
                    "LIQUID_STAKING",
                    9,
                    "jupiter_verified_token_api",
                    "VERIFIED",
                    true,
                    true),
            new SolanaTokenizedDefiAssetDefinition(
                    "vSoLxydx6akxyMD9XEcPvGYNGq6Nn66oqVb3UkGkei7",
                    "vSOL",
                    "the-vault",
                    "The Vault",
                    "LIQUID_STAKING",
                    9,
                    "jupiter_verified_token_api",
                    "VERIFIED",
                    true,
                    true),
            new SolanaTokenizedDefiAssetDefinition(
                    "7Q2afV64in6N6SeZsAAB81TJzwDoD6zpqmHkzi9Dcavn",
                    "JSOL",
                    "jpool",
                    "JPool",
                    "LIQUID_STAKING",
                    9,
                    "jupiter_verified_token_api",
                    "VERIFIED",
                    true,
                    true),
            new SolanaTokenizedDefiAssetDefinition(
                    "Bybit2vBJGhPF52GBdNaQfUJ6ZpThSgHBobjWZpLPb4B",
                    "bbSOL",
                    "bybit",
                    "Bybit Staked SOL",
                    "LIQUID_STAKING",
                    9,
                    "jupiter_verified_token_api",
                    "VERIFIED",
                    true,
                    true),
            new SolanaTokenizedDefiAssetDefinition(
                    "edge86g9cVz87xcpKpy3J77vbp4wYd9idEV562CCntt",
                    "edgeSOL",
                    "edgevana",
                    "Edgevana",
                    "LIQUID_STAKING",
                    9,
                    "jupiter_verified_token_api",
                    "VERIFIED",
                    true,
                    true),
            new SolanaTokenizedDefiAssetDefinition(
                    "stke7uu3fXHsGqKVVjKnkmj65LRPVrqr4bLG2SJg7rh",
                    "STKESOL",
                    "sol-strategies",
                    "STKESOL by SOL Strategies",
                    "LIQUID_STAKING",
                    9,
                    "jupiter_verified_token_api",
                    "VERIFIED",
                    true,
                    true),
            new SolanaTokenizedDefiAssetDefinition(
                    "jag58eRBC1c88LaAsRPspTMvoKJPbnzw9p9fREzHqyV",
                    "jagSOL",
                    "jagpool",
                    "JagPool Staked SOL",
                    "LIQUID_STAKING",
                    9,
                    "jupiter_verified_token_api",
                    "VERIFIED",
                    true,
                    true),
            new SolanaTokenizedDefiAssetDefinition(
                    "sctmB7GPi5L2Q5G9tUSzXvhZ4YiDMEGcRov9KfArQpx",
                    "dfdvSOL",
                    "dfdv",
                    "DFDV Staked SOL",
                    "LIQUID_STAKING",
                    9,
                    "jupiter_verified_token_api",
                    "VERIFIED",
                    true,
                    true),
            new SolanaTokenizedDefiAssetDefinition(
                    "he1iusmfkpAdwvxLNGV8Y1iSbj4rUy6yMhEA3fotn9A",
                    "hSOL",
                    "helius",
                    "Helius Staked SOL",
                    "LIQUID_STAKING",
                    9,
                    "jupiter_verified_token_api",
                    "VERIFIED",
                    true,
                    true),
            new SolanaTokenizedDefiAssetDefinition(
                    "hy1oXYgrBW6PVcJ4s6s2FKavRdwgWTXdfE69AxT7kPT",
                    "hyloSOL",
                    "hylo",
                    "Hylo",
                    "LIQUID_STAKING",
                    9,
                    "jupiter_verified_token_api",
                    "VERIFIED",
                    true,
                    true),
            new SolanaTokenizedDefiAssetDefinition(
                    "hy1opf2bqRDwAxoktyWAj6f3UpeHcLydzEdKjMYGs2u",
                    "hyloSOL+",
                    "hylo",
                    "Hylo SOL Plus",
                    "LIQUID_STAKING",
                    9,
                    "jupiter_verified_token_api",
                    "VERIFIED",
                    true,
                    true),
            new SolanaTokenizedDefiAssetDefinition(
                    "roxDFxTFHufJBFy3PgzZcgz6kwkQNPZpi9RfpcAv4bu",
                    "RoXSOL",
                    "rockawayx",
                    "RockawayX",
                    "LIQUID_STAKING",
                    9,
                    "jupiter_verified_token_api",
                    "VERIFIED",
                    true,
                    true));

    public List<SolanaTokenizedDefiAssetDefinition> enabledDefinitions() {
        return DEFINITIONS;
    }
}
